// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function Connect(arg1:number):Promise<entity.Response_struct____>;

export function CreateConnection(arg1:string,arg2:string,arg3:string):Promise<entity.Response_wails_postgres_panel_connection_Connection_>;

export function ExecuteQuery(arg1:number,arg2:string):Promise<entity.Response_wails_postgres_panel_connection_ExecutionResult_>;

export function GetAllConnections():Promise<entity.Response___wails_postgres_panel_connection_Connection_>;
