// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateConnection'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetAllConnections() {
  return window['go']['main']['App']['GetAllConnections']();
}
